language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed:v4 ydt1/udagram-api-feed:v4
  - docker tag udagram-api-user:v4 ydt1/udagram-api-user:v4
  - docker tag udagram-frontend:v4 ydt1/udagram-frontend:v4
  - docker tag reverseproxy:v4 ydt1/reverseproxy:v4

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ydt1/udagram-api-feed:v4
  - docker push ydt1/udagram-api-user:v4
  - docker push ydt1/udagram-frontend:v4
  - docker push ydt1/reverseproxy:v4